# Generated by Django 4.1.3 on 2022-12-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='varient',
        ),
        migrations.AddField(
            model_name='variation',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='variation_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
