# Generated by Django 4.1.3 on 2022-12-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variation', '0002_remove_size_varient_variation_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
