# Generated by Django 4.1.2 on 2022-10-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
