# Generated by Django 4.1.2 on 2022-11-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_wishlist_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
