# Generated by Django 4.1.3 on 2022-12-09 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referal_id', models.CharField(default=0, max_length=200)),
                ('is_used', models.BooleanField(default=False)),
                ('used_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
