# Generated by Django 4.1.3 on 2022-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_referalsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_id',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
