# Generated by Django 4.1.2 on 2022-10-28 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_descrption',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0=default, 1=Hidden'),
        ),
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, help_text='0=default, 1=Trending'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cata_img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/p_img'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('small_description', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('quantity', models.IntegerField(blank=True)),
                ('original_price', models.FloatField(blank=True)),
                ('selling_price', models.FloatField(blank=True)),
                ('cata_img', models.ImageField(blank=True, null=True, upload_to='img/p_img')),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_title', models.CharField(max_length=150, null=True)),
                ('meta_keywords', models.CharField(max_length=150, null=True)),
                ('meta_descrption', models.CharField(max_length=500, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
