# Generated by Django 4.1.2 on 2022-10-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_meta_descrption_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
