# Generated by Django 4.1.2 on 2022-10-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='meta_descrption',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
        migrations.RemoveField(
            model_name='products',
            name='cata_img',
        ),
        migrations.RemoveField(
            model_name='products',
            name='meta_descrption',
        ),
        migrations.RemoveField(
            model_name='products',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='products',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='products',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='products',
            name='trending',
        ),
        migrations.AddField(
            model_name='products',
            name='Added_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img1',
            field=models.ImageField(blank=True, null=True, upload_to='img/product'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to='img/product'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_img3',
            field=models.ImageField(blank=True, null=True, upload_to='img/product'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=50, unique=True)),
                ('Sub_slug', models.CharField(max_length=50, unique=True)),
                ('Sub_img', models.ImageField(blank=True, null=True, upload_to='imgs/sub')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.subcategory'),
            preserve_default=False,
        ),
    ]
