# Generated by Django 4.1.2 on 2022-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_meta_descrption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Added_Date',
            new_name='added_Date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='small_description',
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
