# Generated by Django 4.1.2 on 2022-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_added_date_products_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_img1',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_img3',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product'),
        ),
    ]
