# Generated by Django 4.1.2 on 2022-10-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_products_product_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_img4',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/product'),
        ),
    ]
