# Generated by Django 4.1.3 on 2022-11-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_alter_category_cata_img_alter_products_product_img1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='margin_price',
            field=models.FloatField(default=0),
        ),
    ]
