# Generated by Django 4.1.3 on 2022-11-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_products_margin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='margin_price',
            field=models.FloatField(),
        ),
    ]
