# Generated by Django 4.1.3 on 2022-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_remove_products_margin_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='margin_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
