# Generated by Django 4.1.3 on 2022-11-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_remove_products_margin_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity', models.BooleanField(default=True)),
                ('product_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.products')),
            ],
        ),
    ]
