# Generated by Django 4.1.3 on 2022-11-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_offer_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer_product',
            old_name='product_name',
            new_name='product',
        ),
    ]
