# Generated by Django 4.1.3 on 2022-11-29 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0015_rename_product_name_offer_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.products'),
        ),
    ]
