# Generated by Django 4.1.3 on 2022-11-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_alter_offer_product_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_product',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.products'),
        ),
    ]
