# Generated by Django 4.1.3 on 2022-11-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0017_alter_offer_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
