# Generated by Django 4.1.3 on 2022-11-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0019_remove_products_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
