# Generated by Django 4.1.3 on 2022-11-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0021_products_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Offer_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity', models.BooleanField(default=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
