# Generated by Django 4.1.3 on 2022-11-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0022_category_discount_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category_offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
