# Generated by Django 4.1.3 on 2022-11-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0023_products_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
