# Generated by Django 4.1.3 on 2022-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0024_alter_products_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='offer',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
