# Generated by Django 4.1.3 on 2022-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0025_alter_category_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
