# Generated by Django 4.1.3 on 2022-12-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0026_products_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='varient_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
