# Generated by Django 4.1.3 on 2022-12-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0027_products_varient_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='varient_price',
        ),
    ]
