# Generated by Django 4.1.3 on 2022-12-01 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupen_code', models.CharField(max_length=200)),
                ('coupen_limit', models.IntegerField()),
                ('validity_upto', models.DateField()),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxLengthValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
