# Generated by Django 4.1.3 on 2022-12-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupens',
            name='used_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
