# Generated by Django 4.1.3 on 2022-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0002_coupens_used_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupens',
            name='used_at',
        ),
        migrations.AddField(
            model_name='coupens',
            name='is_used',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
