# Generated by Django 4.1.3 on 2022-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupen', '0003_remove_coupens_used_at_coupens_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupens',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
