# Generated by Django 4.1.2 on 2022-11-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_oldcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldcart',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
