# Generated by Django 4.1.3 on 2022-11-25 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_gcart_remove_oldcart_cart_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='Guest',
        ),
    ]
