# Generated by Django 4.1.3 on 2022-11-25 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_cart_cartitem_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcart',
            old_name='cart_id',
            new_name='Guest_id',
        ),
    ]
