# Generated by Django 4.1.3 on 2022-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_cart_id_gcart_guest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='applayed_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
