# Generated by Django 4.1.3 on 2022-12-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cartitem_applayed_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='applayed_price',
        ),
    ]
