# Generated by Django 4.1.3 on 2022-12-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_cartitem_applayed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varient_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
