# Generated by Django 4.1.3 on 2022-12-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartitem_varient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='varient_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
