# Generated by Django 4.1.2 on 2022-11-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_price_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
