# Generated by Django 4.1.3 on 2022-12-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_order_id_alter_orders_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='grand_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='offered_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
