# Generated by Django 4.1.3 on 2022-12-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_grand_price_orders_offered_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupen_applied',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
