# Generated by Django 4.1.3 on 2022-12-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_variation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='variation_id',
            field=models.CharField(default=0, max_length=500, null=True),
        ),
    ]
